### ISSUE TITLE
Can't scroll

### ISSUE THREAD

**Issue by zethon** [jasonbio/reddit-shell#11]
I use `https://redditshell.com/` often when I'm in the office since it's more innocuous but a few months ago I noticed that I was no longer able to scroll. I figured this had something to do with my work's firewall since weird things always happen because of the firewall. I decided to use `https://redditshell.com/ ` tonight while I'm out and about (and being lame and using my laptop at a bar) and sure enough, I'm unable to scroll. WTF?

BTW: Chrome Version 62.0.3202.94 (Official Build) (64-bit)
OSX: 10.11.6

**Comment by nikwilliamson** [comment]
Just added a PR for a fix for this. https://github.com/jasonbio/reddit-shell/pull/12

**Comment by jcubic** [comment]
Better would be to update jQuery Terminal because I made mistake and use browser sniff to detect Google Chrome. Google was using html as scroll element and they changed their mind it's now the same as in other browsers.

The other issue that will not be fixed unless you update the library is scroll to bottom on keypress.

**Comment by jasonbio** [comment]
This has been fixed with 7841b82
