### ISSUE TITLE
Loading comments over HTTP instead of HTTPS

### ISSUE THREAD

**Issue by emitchel** [jasonbio/reddit-shell#8]
Error retrieving comments over HTTP instead of HTTPS

**Comment by asadw1** [comment]
I experienced similar issues. Was it error fetching data?

**Comment by emitchel** [comment]
![image](https://cloud.githubusercontent.com/assets/3791583/12646542/5703288a-c596-11e5-8dff-7e7cc9cd8663.png)

Seems to be a simple fix

**Comment by jasonbio** [comment]
Weird, it should request everything over HTTPS by default.. wondering if maybe reddit was temporarily downgrading requests to HTTP. Can't reproduce right now anyways.

**Comment by alminisl** [comment]
I get the same issue when I want to load some Posts.

**Comment by jasonbio** [comment]
Can you please provide me with some console logs and network requests? Also what commands were you typing? I can't seem to replicate this myself so I'm having trouble figuring out what the problem is.

My only theory is that the "view comments" command is requesting "https://reddit.com/r/subreddit/comments/4dthkd/etc..." instead of "https://www.reddit.com/r/subreddit/comments/4dthkd/etc..." (missing the www) which seems to result in a 301 Moved Permanently response in certain cases and then forwards to "https://www.reddit.com/r/subreddit/comments/4dthkd/etc...". Not sure why the request would be downgraded after the 301 response, but it's possible I guess.

**Comment by jasonbio** [comment]
I addressed this issue in my latest commit - hopefully this helps 4323c5ee18c124f876a55e828126f0bd309bf229
